name: Deploy to HuggingFace Space

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Sync backend to HuggingFace Space
      uses: nateraw/huggingface-sync-action@v0.0.5
      with:
        github_repo_id: ${{ github.repository }}
        huggingface_repo_id: ${{ secrets.HF_SPACE_ID }}
        hf_token: ${{ secrets.HF_TOKEN }}
        repo_type: space
        private: false
        space_sdk: docker
        subdirectory: backend
