name: Deploy to HuggingFace Space

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Sync backend to HuggingFace Space
      uses: huggingface/sync-repo-to-hub@v0.1
      with:
        hf_token: ${{ secrets.HF_TOKEN }}
        repo_id: ${{ secrets.HF_SPACE_ID }}
        repo_type: space
        path: backend
        space_sdk: docker
        space_hardware: cpu-basic
        space_sleep_time: 0
        space_secrets: |
          AURORA_DB_URL=${{ secrets.AURORA_DB_URL }}
          MYSQL_SSL_CA_PATH=/app/ca.pem
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          AURORA_HMAC_KEY=${{ secrets.AURORA_HMAC_KEY }}
          AURORA_ENV=production
          AURORA_INDEX_VERSION=v1
          CHROMA_DIR=./chroma_store
